# Generated by Django 3.0.6 on 2020-06-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aut_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aut_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('book_editorial', models.CharField(max_length=50)),
                ('book_saga', models.CharField(max_length=50)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_price_dis', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cli_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=50, null=True)),
                ('cli_ape', models.CharField(max_length=50, null=True)),
                ('cli_email', models.CharField(max_length=50)),
                ('cli_cc_fecha_expedicion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('gen_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gen_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ord_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ord_pay_id', models.CharField(max_length=10)),
                ('ord_ord_date', models.DateField(auto_now=True)),
                ('ord_pay_date', models.DateField()),
                ('ord_cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=20)),
                ('pay_allow', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Details',
            fields=[
                ('od_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('od_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Book')),
                ('od_ord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bxg_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Book')),
                ('bxg_gen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bxa_aut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Author')),
                ('bxa_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Book')),
            ],
        ),
    ]
